version: '2'
services:
  web:
    build: .
    command: bash script/dev/setup.sh
    environment:
      - PORT=4000
      - MIX_ENV=dev
      - DB_ENV_POSTGRES_USER=postgres
      - DB_ENV_POSTGRES_PASSWORD=postgres
      - DB_ENV_POSTGRES_HOST=dev_db
      - DB_ENV_NAME=teebox_dev
    volumes:
      - .:/app
      - /var/run/docker.sock:/tmp/sock
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "4000:4000"
    privileged: true
    depends_on:
      - dev_db

  dev_db:
    image: postgres

  test:
    image: teebox_web
    volumes_from:
      - web
    command: mix test
    environment:
      - MIX_ENV=test
      - PORT=4001
      - DB_ENV_POSTGRES_USER=postgres
      - DB_ENV_POSTGRES_PASSWORD=postgres
      - DB_ENV_POSTGRES_HOST=test_db
      - DB_ENV_NAME=teebox_test
    depends_on:
      - test_db

  test_db:
    image: postgres

  run_release:
    image: dodgerogers/teebox:release
    command: foreground
    environment:
      - MIX_ENV=prod
      - PORT=5001
      - SECRET_KEY_BASE=secret_key_base
      - DB_ENV_POSTGRES_USER=postgres
      - DB_ENV_POSTGRES_PASSWORD=postgres
      - DB_ENV_POSTGRES_HOST=release_db
      - DB_ENV_NAME=teebox_release
    ports:
      - "5001:5001"
    depends_on:
      - release_db

  release_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=teebox_release
