FROM bitwalker/alpine-erlang:21.0.9

RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ && \
    rm -rf /var/cache/apk/*

EXPOSE 5001
ENV PORT=5001 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ADD teebox.tar.gz ./
RUN chown -R default ./releases

USER default

ENTRYPOINT ["/opt/app/bin/teebox"]
